name = "Flawlessly Optimized [Experimental]"
author = "chizusrevenge"
version = "1.0.1-Experimental"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07490ed06415ac46afc062e773996ce37aaf073b6d0d14df9399a5d5d8f52695"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
