name = "Flawlessly Optimized [Experimental]"
author = "chizusrevenge"
version = "1.0.0-Experimental"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7758ccbbe05622eac47807e7c3489f266e0a7676b2d0d010a8a20ca8c5c7d75a"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
