name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.1.3-Experimental"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f975550b4336f780aed926e881ccf6cb90c1030d00d9e1839451fd3fa43a52fd"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
