name = "Flawlessly Optimized [Experimental]"
author = "chizusrevenge"
version = "1.0.0-Experimental"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f05cae27b40114b42e5b20870ce2f0418fbd400e4ed6cead90d795cb97b18b1f"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
