name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.1.4-Experimental"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5448fa1fd8fd929cd9da3d6497af59e6ab44aa84f8fabd3c4cf74b75b4873389"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
