name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.1.2-Experimental"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a55497aa5f504ffd3675dca36525026d1e115c83d0019ea5cee10ce9af013e51"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
