name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.1.1-Experimental"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea85350c52247e1917edeeae8d99e441a02bb06efc00c1d575b6af3422ed6da7"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
