name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b87aca34d76bebca5f4fdac9090d001ec77cf1e9d0afb439e8c0c96e6cc99dfe"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
