name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20621d4c83a606f93ed829124236d3cbb87ef9760fe31c8aab4a4956da1c6d2d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
