name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.3.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a4526eb7e33a463c0fe93ddd51da85f9ac4aef062a9416e4a810ecafa6e191f"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
