name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.1.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dff7d28632aa4935960bda6c6b49a789207ba2c0353c70b47782cb99463996e5"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
