name: Bug report
description: Report an issue with the modpack in its unmodified state.
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Before reporting an issue, [please search](https://github.com/chizusrevenge/Flawlessly-Optimized/issues) to make sure it has not already been reported. 

- type: textarea
  attributes:
    label: Describe the bug
    description: Describe your problem in detail.
  validations:
    required: true

- type: input
  attributes:
    label: Modpack version
    description: What version of the modpack are you using?
    placeholder: Find it in the bottom right corner of the main menu
  validations:
    required: true

- type: dropdown
  attributes:
    label: Launcher
    description: Which launcher are you using?
    options:
      - Modrinth App
      - Prism Launcher
      - MultiMC
      - Other
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Confirm
    options:
      - label: This bug report is about an issue with the modpack itself, I have not modified the mods or added any resource packs.
        required: true
    
- type: textarea
  attributes:
    label: Additional context
    description: Screenshots, video or any other information. If it is a crash, please post it to [mclo.gs](https://mclo.gs/) and add a link here.
    placeholder: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false