name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.4.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ed0aa70d20bd028ca642aec44db93f5538108bf04372a4500cbbe2c40e3ac68"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
