name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.6.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6104727de68432a1e16093020e85d9137a5a57ae71320061da17a2eaad9f44fb"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
