name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7656aed834745c5c806b175d87c445e05e8c088370d07f87ea665f089010547"

[versions]
fabric = "0.16.7"
minecraft = "1.21.3"
