name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.7.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b38751d1427a9f3ad76b0808ede9aa6f26a10e57b208607ac67f34841e510dfb"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
