name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.3.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbb1113dd8e3685652f42176495173ac62d7c896692a0bd363b2bdee4a49e78a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
