name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.7.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc81b6adc99e15ec7e471a417bf5a3d8c75b276929dc6bd7caea5c8883b14cc9"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
