name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.6.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d0a31eb1431b2271ed48a69f596626a7c6dd82ef807dfbc0200413a4fc67a89"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
