name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.4.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa7333e5e5f2e51caec9212c9e8320ea2dc4ffa3ff9d08f817491edb4a6b3c19"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
