name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45f41fce859d510b8692e70b8aa60d9858d16b278f3d59e3ac1fa70f6156d447"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
