name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c67d42b52e3229435cdd60b24d69b4ca472ce8cb502515d2fb8c4e4b1cbe5378"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
