name = "Flawlessly Optimized"
author = "chizusrevenge"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cefe248d941053923b34e06929de83741ea26febc2cd1f948f4cf18c90c90085"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
